### ISSUE TITLE
SearchClosest Fatal Error: Could not find the template SiteMaster/Core/Registry/SearchClosest.tpl.php

### ISSUE THREAD

**Issue by alexfinnarn** [CuBoulder/site_master#12]
`Fatal error: Uncaught Savvy_TemplateException: Could not find the template SiteMaster/Core/Registry/SearchClosest.tpl.php in /var/www/html/vendor/saltybeagle/savvy/src/Savvy.php:690`

On `registry/closest/` route. I have no idea what this page is supposed to do. You need some reference to a site, but what does "closest" mean?

**Comment by mfairchild365** [comment]
Great question. "Closest" means the site that first matches the query. For example "https://www.unl.edu/band/cornhusker-marching-band-schedule" could match the registered sites at https://www.unl.edu/band/ and https://www.unl.edu/ but some API calls just want to get the "closest" site which would be https://www.unl.edu/band/.

We never had a need to implement an HTML version of this, so only JSON is implemented. 

Example:

https://webaudit.unl.edu/registry/closest/?query=https%3A%2F%2Fwww.unl.edu%2Fband%2Fcornhusker-marching-band-schedule&format=json
