### ISSUE TITLE
Approve Pending Roles Error

### ISSUE THREAD

**Issue by alexfinnarn** [CuBoulder/site_master#13]
As an admin user who can access "admin/*" routes, I cannot approve my roles for a site. I get an error.

> Whoops! Sorry, there was an error: Invalid security token provided. If you think this was an error, please retry the request.

<img width="762" alt="screen shot 2018-09-25 at 3 42 06 pm" src="https://user-images.githubusercontent.com/3640707/46047335-98469980-c0d9-11e8-9b6d-984eb1829a27.png">

**Comment by mfairchild365** [comment]
This form appears to be missing a CSRF token. See https://github.com/UNLSiteMaster/site_master/issues/154
