### ISSUE TITLE
Scope Express Navbar integration

### ISSUE THREAD

**Issue by kreynen** [CuBoulder/site_master#18]
@kevincrafts created a prototype for how this could work when we were looking at Site Improve and Tenon in https://github.com/CuBoulder/express/issues/1967

UNL links to Web Audit in their standard footer.

![university_of_nebraska lincoln](https://user-images.githubusercontent.com/385234/46098427-9afcc980-c181-11e8-8f51-775952863474.png)

Initially, we aren't going to make the scan results public, but we want to be able to enable the "score" in Express sometime in 2019.  

I think this would require a new route that returns the score of any page url it is given.

**Comment by alexfinnarn** [comment]
from #11, I found "sites/{site_id}/scan/page/?uri=" and "sites/{site_id}/pages/{page_id}/". The "{page_id}" parameter probably doesn't help but the URI query parameter should allow for a pattern to create links from. Each Express site would have to know its site_id.
