### ISSUE TITLE
Add additional attributes to sites

### ISSUE THREAD

**Issue by kreynen** [CuBoulder/site_master#5]
- [ ] Organization (from directory)
- [ ] Display in Directory option
- [ ] Type (service/student group/faculty/labs/events etc)

The type of site will impact the elements of the new brand standard a site is required to use.  For the Express sites, it will apply them before the site launches.

**Comment by alexfinnarn** [comment]
I think https://github.com/CuBoulder/site_master/blob/master/src/SiteMaster/Core/Registry/Site.php is the definition of the Site "Record".

The Site class mainly deals with the Site data model and how to retrieve and create Sites and site data; however, there are also methods like `scheduleScan()` which requires that class to know about `SiteMaster\Core\Auditor\Scan`. 

The coupling doesn't seem necessary to me. I would associate scans with sites via IDs and foreign keys. Then a service would handle scheduling the scan for a site. `$this->scheduler->addTask('site_scan', $this->scanner, $this->site);`

**Comment by alexfinnarn** [comment]
Also keep in mind that the Site record class is stored in `SiteMaster\Core\Registry` but has to know about `SiteMaster\Core\Auditor\Site`. What does Auditor mean in the context of the business domain language?
